---
postgresql_global_config_options:
  - option: listen_addresses
    value: '*'
  - option: data_directory
    value: '/mnt/pg_data/main'
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: log_directory
    value: 'log'
  - option: max_connections
    value: '30'
  - option: shared_buffers
    value: '4GB'
  - option: effective_cache_size
    value: '12GB'
  - option: maintenance_work_mem
    value: '1GB'
  - option: checkpoint_completion_target
    value: '0.9'
  - option: wal_buffers
    value: '16MB'
  - option: default_statistics_target
    value: '100'
  - option: random_page_cost
    value: '1.1'
  - option: effective_io_concurrency
    value: '200'
  - option: work_mem
    value: '123361kB'
  - option: huge_pages
    value: 'off'
  - option: min_wal_size
    value: '1GB'
  - option: max_wal_size
    value: '4GB'
  - option: max_worker_processes
    value: '4'
  - option: max_parallel_workers_per_gather
    value: '2'
  - option: max_parallel_workers
    value: '4'
  - option: max_parallel_maintenance_workers
    value: '2'
  - option: checkpoint_timeout
    value: '30'
  - option: logging_collector
    value: 'on'
  - option: log_checkpoints
    value: 'on'
postgresql_users:
  - name: postgres
    password: postgres
postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}"}
  - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
